### ISSUE TITLE
Websocketpp exception

### ISSUE THREAD

**Issue by Brandantl** [yourWaifu/sleepy-discord#75]
```
"terminate called after throwing an instance of 'websocketpp::exception'
  what():  Invalid close code used
Aborted (core dumped)"
```
This exception isn't being handled by sleepy. I have no trace traces or any other information i compiled accidentally w/o symbols. Will report back if repeatable.

**Comment by yourWaifu** [comment]
I don't know anywhere in my code where exception is thrown outside of here https://github.com/yourWaifu/sleepy-discord/blob/develop/sleepy_discord/websocketpp_websocket.cpp#L91

**Comment by Brandantl** [comment]
This still occurs
```
<asio::basic_waitable_timer<std::chrono::_V2::steady_clock, asio::wait_traits<std::chrono::_V2::steady_clock> > >, std::function<void (std::error_code const&)>, std::_Placeholder<1>)>::operator()<std::error_code const&, void>(std::error_code const&) ()
#24 0x0000555555ab01ff in asio::detail::binder1<std::_Bind<std::_Mem_fn<void (websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>::*)(std::shared_ptr<asio::basic_waitable_timer<std::chrono::_V2::steady_clock, asio::wait_traits<std::chrono::_V2::steady_clock> > >, std::function<void (std::error_code const&)>, std::error_code const&)> (websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>*, std::shared_ptr<asio::basic_waitable_timer<std::chrono::_V2::steady_clock, asio::wait_traits<std::chrono::_V2::steady_clock> > >, std::function<void (std::error_code const&)>, std::_Placeholder<1>)>, std::error_code>::operator()() ()
#25 0x0000555555aa9152 in void asio::asio_handler_invoke<asio::detail::binder1<std::_Bind<std::_Mem_fn<void (websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>::*)(std::shared_ptr<asio::basic_waitable_timer<std::chrono::_V2::steady_clock, asio::wait_traits<std::chrono::_V2::steady_clock> > >, std::function<void (std::error_code const&)>, std::error_code const&)> (websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>*, std::shared_ptr<asio::basic_waitable_timer<std::chrono::_V2::steady_clock, asio::wait_traits<std::chrono::_V2::steady_clock> > >, std::function<void (std::error_code const&)>, std::_Placeholder<1>)>, std::error_code> >(asio::detail::binder1<std::_Bind<std::_Mem_fn<void (websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>::*)(std::shared_ptr<asio::basic_waitable_timer<std::chrono::_V2::steady_clock, asio::wait_traits<std::chrono::_V2::steady_clock> > >, std::function<void (std::error_code const&)>, std::error_code const&)> (websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>*, std::shared_ptr<asio::basic_waitable_timer<std::chrono::_V2::steady_clock, asio::wait_traits<std::chrono::_V2::steady_clock> > >, std::function<void (std::error_code const&)>, std::_Placeholder<1>)>, std::error_code>&, ...) ()
#26 0x0000555555aa037b in void asio_handler_invoke_helpers::invoke<asio::detail::binder1<std::_Bind<std::_Mem_fn<void (websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>::*)(std::shared_ptr<asio::basic_waitable_timer<std::chrono::_V2::steady_clock, asio::wait_traits<std::chrono::_V2::steady_clock> > >, std::function<void (std::error_code const&)>, std::error_code const&)> (websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>*, std::shared_ptr<asio::basic_waitable_timer<std::chrono::_V2::steady_clock, asio::wait_traits<std::chrono::_V2::steady_clock> > >, std::function<void (std::error_code const&)>, std::_Placeholder<1>)>, std::error_code>, std::_Bind<std::_Mem_fn<void (websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>::*)(std::shared_ptr<asio::basic_waitable_timer<std::chrono::_V2::steady_clock, asio::wait_traits<std::chrono::_V2::steady_clock> > >, std::function<void (std::error_code const&)>, std::error_code const&)> (websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>*, std::shared_ptr<asio::basic_waitable_timer<std::chrono::_V2::steady_clock, asio::wait_traits<std::chrono::_V2::steady_clock> > >, std::function<void (std::error_code const&)>, std::_Placeholder<1>)> >(asio::detail::binder1<std::_Bind<std::_Mem_fn<void (websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>::*)(std::shared_ptr<asio::basic_waitable_timer<std::chrono::_V2::steady_clock, asio::wait_traits<std::chrono::_V2::steady_clock> > >, std::function<void (std::error_code const&)>, std::error_code const&)> (websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>*, std::shared_ptr<asio::basic_waitable_timer<std::chrono::_V2::steady_clock, asio::wait_traits<std::chrono::_V2::steady_clock> > >, std::function<void (std::error_code const&)>, std::_Placeholder<1>)>, std::error_code>&, std::_Bind<std::_Mem_fn<void (websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>::*)(std::shared_ptr<asio::basic_waitable_timer<std::chrono::_V2::steady_clock, asio::wait_traits<std::chrono::_V2::steady_clock> > >, std::function<void (std::error_code const&)>, std::error_code const&)> (websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>*, std::shared_ptr<asio::basic_waitable_timer<std::chrono::_V2::steady_clock, asio::wait_traits<std::chrono::_V2::steady_clock> > >, std::function<void (std::error_code const&)>, std::_Placeholder<1>)>&) ()
#27 0x0000555555a94c69 in void asio::detail::handler_work<std::_Bind<std::_Mem_fn<void (websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>::*)(std::shared_ptr<asio::basic_waitable_timer<std::chrono::_V2::steady_clock, asio::wait_traits<std::chrono::_V2::steady_clock> > >, std::function<void (std::error_code const&)>, std::error_code const&)> (websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>*, std::shared_ptr<asio::basic_waitable_timer<std::chrono::_V2::steady_clock, asio::wait_traits<std::chrono::_V2::steady_clock> > >, std::function<void (std::error_code const&)>, std::_Placeholder<1>)>, asio::system_executor>::complete<asio::detail::binder1<std::_Bind<std::_Mem_fn<void (websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>::*)(std::shared_ptr<asio::basic_waitable_timer<std::chrono::_V2::steady_clock, asi---Type <return> to continue, or q <return> to quit---
o::wait_traits<std::chrono::_V2::steady_clock> > >, std::function<void (std::error_code const&)>, std::error_code const&)> (websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>*, std::shared_ptr<asio::basic_waitable_timer<std::chrono::_V2::steady_clock, asio::wait_traits<std::chrono::_V2::steady_clock> > >, std::function<void (std::error_code const&)>, std::_Placeholder<1>)>, std::error_code> >(asio::detail::binder1<std::_Bind<std::_Mem_fn<void (websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>::*)(std::shared_ptr<asio::basic_waitable_timer<std::chrono::_V2::steady_clock, asio::wait_traits<std::chrono::_V2::steady_clock> > >, std::function<void (std::error_code const&)>, std::error_code const&)> (websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>*, std::shared_ptr<asio::basic_waitable_timer<std::chrono::_V2::steady_clock, asio::wait_traits<std::chrono::_V2::steady_clock> > >, std::function<void (std::error_code const&)>, std::_Placeholder<1>)>, std::error_code>&, std::_Bind<std::_Mem_fn<void (websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>::*)(std::shared_ptr<asio::basic_waitable_timer<std::chrono::_V2::steady_clock, asio::wait_traits<std::chrono::_V2::steady_clock> > >, std::function<void (std::error_code const&)>, std::error_code const&)> (websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>*, std::shared_ptr<asio::basic_waitable_timer<std::chrono::_V2::steady_clock, asio::wait_traits<std::chrono::_V2::steady_clock> > >, std::function<void (std::error_code const&)>, std::_Placeholder<1>)>&) ()
#28 0x0000555555a8b81b in asio::detail::wait_handler<std::_Bind<std::_Mem_fn<void (websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>::*)(std::shared_ptr<asio::basic_waitable_timer<std::chrono::_V2::steady_clock, asio::wait_traits<std::chrono::_V2::steady_clock> > >, std::function<void (std::error_code const&)>, std::error_code const&)> (websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>*, std::shared_ptr<asio::basic_waitable_timer<std::chrono::_V2::steady_clock, asio::wait_traits<std::chrono::_V2::steady_clock> > >, std::function<void (std::error_code const&)>, std::_Placeholder<1>)> >::do_complete(void*, asio::detail::scheduler_operation*, std::error_code const&, unsigned long) ()
#29 0x0000555555a5760c in asio::detail::scheduler_operation::complete(void*, std::error_code const&, unsigned long) ()
#30 0x0000555555a5b40c in asio::detail::scheduler::do_run_one(asio::detail::conditionally_enabled_mutex::scoped_lock&, asio::detail::scheduler_thread_info&, std::error_code const&) ()
#31 0x0000555555a5ad97 in asio::detail::scheduler::run(std::error_code&) ()
#32 0x0000555555a5b9d8 in asio::io_context::run() ()
#33 0x0000555555a69fbb in websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>::run() ()
#34 0x0000555555aebdaf in unsigned long std::_Mem_fn_base<unsigned long (websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>::*)(), true>::_M_call<websocketpp::client<websocketpp::config::asio_tls_client>*>(websocketpp::client<websocketpp::config::asio_tls_client>*&&, void const volatile*) const ()
#35 0x0000555555aeb89c in unsigned long std::_Mem_fn_base<unsigned long (websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>::*)(), true>::operator()<websocketpp::client<websocketpp::config::asio_tls_client>*, , void>(websocketpp::client<websocketpp::config::asio_tls_client>*&&) const ()
#36 0x0000555555aeb157 in unsigned long std::_Bind_simple<std::_Mem_fn<unsigned long (websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>::*)()> (websocketpp::client<websocketpp::config::asio_tls_client>*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) ()
#37 0x0000555555aea01a in std::_Bind_simple<std::_Mem_fn<unsigned long (websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>::*)()> (websocketpp::client<websocketpp::config::asio_tls_client>*)>::operator()() ()
#38 0x0000555555ae7830 in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<unsigned long (websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>::*)()> (websocketpp::client<websocketpp::config::asio_tls_client>*)> >::_M_run() ()
#39 0x00007ffff63aaae4 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#40 0x00007ffff6fab6db in start_thread (arg=0x7fffef9f9700) at pthread_create.c:463
#41 0x00007ffff5e0488f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by yourWaifu** [comment]
That call stack looks similar to another one from a bug that I fixed like months ago.

**Comment by Brandantl** [comment]
This is actually quite hard to reproduce. I'll report back in a couple of more days.
![image](https://user-images.githubusercontent.com/6909044/44315242-0a3f0b00-a3d7-11e8-9752-53f00b5ea8e9.png)
